id: I66073611
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T11:14:03+00:00'
last_modified: '2022-06-08T08:56:03.804681+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG987
  title: མདོ་མཁྱེན་བརྩེ་ཡེ་ཤེས་རྡོ་རྗེའི་གདུང་རྒྱུད་རིམ་བྱོན་གྱི་རྣམ་ཐར་གསལ་བའི་མེ་ལོང་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    AC71:
      image_group_id: I1KG1010
      title: ''
      total_pages: 455
      order: 1
      base_file: AC71.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
